<table width="98%" border="0" cellspacing="0" cellpadding="0" class="table_form">
	<tr>
		<th width="120">订单号：</th>
		<td><?=$data['orderno']?></td>
	</tr>
	<tr>
		<th>订阅用户：</th>
		<td><?=$data['username']?>
		</td>
	</tr>
	<tr>
		<th>订阅栏目组：</th>
		<td><?=$payview_category[$data['pvcid']]['title']?>(<?=$payview_category[$data['pvcid']]['timetype']?>个月)</td>
	</tr>
	<tr>
		<th>付费类型：</th>
		<td><?=$data['type_text']?></td>
	</tr>
	<tr>
		<th>订阅开始时间：</th>
		<td><?=$data['starttime']?></td>
	</tr>
	<tr>
		<th>订阅结束时间：</th>
		<td><?=$data['endtime']?></td>
	</tr>
	<tr>
		<th>付费状态：</th>
		<td><?=$data['status_text']?></td>
	</tr>
	<tr>
		<th>订阅费用：</th>
		<td><?=$data['payfee']?> 元</td>
	</tr>
	<tr>
		<th>是否开具发票：</th>
		<td><?=$data['is_invoice_text']?></td>
	</tr>
	<tr>
		<th>发票抬头：</th>
		<td><?=$data['invoice_title']?></td>
	</tr>
	<tr>
		<th>收件人：</th>
		<td><?=$data['post_name']?></td>
	</tr>
	<tr>
		<th>邮寄地址：</th>
		<td><?=$data['post_address']?></td>
	</tr>
	<tr>
		<th>邮寄费用：</th>
		<td><?=$data['post_fees']?></td>
	</tr>
	<tr>
		<th>联系电话：</th>
		<td><?=$data['post_phone']?></td>
	</tr>
	<tr>
		<th>下单时间：</th>
		<td><?=$data['created']?></td>
	</tr>
</table>