// Generated by CoffeeScript 1.6.2
(function() {
  var ShareWeibo,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ShareWeibo = (function() {
    var alertDialog, authWindow, authorize, authorizeError, authorizeSuccess, bind, changeAuthorized, load, selectedShareIco, self, unselectedShareIco,
      _this = this;

    self = alertDialog = authWindow = null;

    function ShareWeibo() {
      this.build = __bind(this.build, this);
      this.init = __bind(this.init, this);      self = this;
      true;
    }

    ShareWeibo.prototype.init = function() {
      var _this = this;

      if (document.readyState === 'loading') {
        return $(function() {
          return load();
        });
      } else {
        return load();
      }
    };

    ShareWeibo.prototype.build = function(data, panel) {
      var html, ico;

      ico = data.is_authorized ? data.icon : data.icon_gray;
      html = $(new Array('<label>' + '<div class="repost-btn">' + '<img src="' + ico + '" alt="' + data["interface"] + '" title="转发到' + data.name + '" />' + '<div class="tick"></div>' + '</div>' + '<input type="checkbox" name="share_weibo[]" value="' + data.apiid + '" style="visibility:hidden;" />' + '</label>').join(''));
      panel.append(html);
      html.find('.repost-btn').bind('click', {
        item: data
      }, function(event) {
        var element;

        if (event.data.item.is_authorized) {
          return bind(this, event);
        } else {
          element = $(this);
          element.bind('changeAuthorized', {
            ico: event.data.item.icon
          }, changeAuthorized);
          return authorize(event.data.item["interface"], element);
        }
      });
      if (data.is_authorized) {
        return setTimeout(function() {
          return html.find('.repost-btn').click();
        }, 10);
      }
    };

    load = function() {
      var url;

      url = "" + APP_URL + "?app=comment&controller=review&action=ajax_allow_weibo&jsoncallback=?";
      return $.getJSON(url, function(res) {
        var panel;

        if (!(res && res.length)) {
          return;
        }
        panel = $('.loginform-user-info').children('.seccode-area');
        $.each(res, function(i, k) {
          return self.build(k, panel);
        });
        return panel.css('visibility', 'visible');
      });
    };

    authorize = function(type, element) {
      var p, params, url;

      url = "" + APP_URL + "?app=cloud&controller=thirdlogin&action=redirect_to_authorize&type=" + type;
      params = 'width=640,height=480,location=no,menubar=no,scrollbars=yes';
      authWindow = window.open(url, void 0, params);
      return p = setInterval(function() {
        var authsuccess;

        if (!authWindow.closed) {
          return;
        }
        authsuccess = $.cookie(COOKIE_PRE + 'authsuccess');
        if (authsuccess === '0') {
          $.cookie(COOKIE_PRE + 'authsuccess', null, {
            domain: COOKIE_DOMAIN
          });
          authorizeSuccess(element);
        } else {
          if (typeof authsuccess === 'string') {
            authorizeError(authsuccess);
          }
        }
        return clearInterval(p);
      }, 1000);
    };

    authorizeSuccess = function(element) {
      return element.trigger('changeAuthorized');
    };

    authorizeError = function(message) {
      if (!alertDialog) {
        alertDialog = new window.dialog({
          hasOverlay: 1,
          width: 180,
          height: 28,
          hasCloseIco: 0,
          closeDelay: 3000
        });
      }
      return alertDialog.open({
        text: message
      });
    };

    changeAuthorized = function(event) {
      var element;

      element = $(this);
      element.find('img').attr('src', event.data.ico);
      element.unbind().bind('click', function(event) {
        return bind(this, event);
      });
      return setTimeout(function() {
        return element.find('.repost-btn').click();
      }, 10);
    };

    bind = function(element, event) {
      var checkbox;

      element = $(element);
      checkbox = element.next('input[type="checkbox"]');
      if (checkbox.is(':checked')) {
        unselectedShareIco(element);
      } else {
        selectedShareIco(element);
      }
      checkbox[0].checked = !checkbox.is(':checked');
      return event.preventDefault();
    };

    selectedShareIco = function(element) {
      return element.addClass('repost-btn-checked').removeClass('repost-btn');
    };

    unselectedShareIco = function(element) {
      return element.addClass('repost-btn').removeClass('repost-btn-checked');
    };

    return ShareWeibo;

  }).call(this);

  window.shareWeibo = new ShareWeibo();

}).call(this);
