// Generated by CoffeeScript 1.4.0
(function() {
  var forceSubmit, warnning, warnningPanel;

  warnningPanel = null;

  forceSubmit = false;

  warnning = function(text) {
    warnningPanel.innerHTML = text;
    return warnningPanel.style.display = 'block';
  };

  window.postForm = function(form) {
    var url;
    if (forceSubmit) {
      return true;
    }
    url = form.video.value;
    if (url.length === 0) {
      return false;
    }
    if (!/^(\w)+:\/\/.*\.swf(\?|&|$)/i.test(url)) {
      $.post("?app=baoliao&controller=index&action=spider&token=" + token, {
        url: url
      }, function(res) {
        if (!res.state) {
          warnning(typeof res.error === 'string' ? res.error : '提示：cmstop暂不支持该网站的播放页地址');
          return false;
        }
        form.video.value = res.url;
        form.thumb.value = res.thumb;
        forceSubmit = true;
        return $('#form').submit();
      }, 'json');
      return false;
    }
    return true;
  };

  window.onload = function() {
    return warnningPanel = document.getElementById('warnning');
  };

}).call(this);
